// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDke4-3p5O0Zx9oMuSPQbkqbbedkSMPb5Y',
    appId: '1:278910587886:web:aa6c8aecda845ad750f4ff',
    messagingSenderId: '278910587886',
    projectId: 'sigma-shop-ba303',
    authDomain: 'sigma-shop-ba303.firebaseapp.com',
    storageBucket: 'sigma-shop-ba303.firebasestorage.app',
    measurementId: 'G-2RN884SHKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSfUT5BfnZZNzVkL3QFiym5oxN_8wY6OU',
    appId: '1:278910587886:android:666d2e7975d02b7350f4ff',
    messagingSenderId: '278910587886',
    projectId: 'sigma-shop-ba303',
    storageBucket: 'sigma-shop-ba303.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKLfdDUwSN-zkZo2JRcsicbZTnnmnuB00',
    appId: '1:278910587886:ios:afedce647c7d618f50f4ff',
    messagingSenderId: '278910587886',
    projectId: 'sigma-shop-ba303',
    storageBucket: 'sigma-shop-ba303.firebasestorage.app',
    iosBundleId: 'com.example.sigma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKLfdDUwSN-zkZo2JRcsicbZTnnmnuB00',
    appId: '1:278910587886:ios:afedce647c7d618f50f4ff',
    messagingSenderId: '278910587886',
    projectId: 'sigma-shop-ba303',
    storageBucket: 'sigma-shop-ba303.firebasestorage.app',
    iosBundleId: 'com.example.sigma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDke4-3p5O0Zx9oMuSPQbkqbbedkSMPb5Y',
    appId: '1:278910587886:web:c4df13cf2e20849b50f4ff',
    messagingSenderId: '278910587886',
    projectId: 'sigma-shop-ba303',
    authDomain: 'sigma-shop-ba303.firebaseapp.com',
    storageBucket: 'sigma-shop-ba303.firebasestorage.app',
    measurementId: 'G-CHV02D7J9F',
  );
}
